### PR TITLE
39-weapons-bullet-range

### PR DESCRIPTION
**Pull request by SmallPeenwow**
For testing I left some Debugs so you notice what is happening and also for you to play with to see what you want.

I would consider making another ground and stretching it out and making the muzzle velocity lower but that will make the bullet drop arch greater but if going at higher speeds it will decrease less from what I can tell.

Also see by changing the Rigidbody mass of the bullet prefab to the bulletweight on the one script to see if you want the bullets to go faster and then from there I can make more adjustments to bullet drop or not or future fix when we have firing range.

Also see how you want the distance to be with the rounded off because the distance won't always be the same even if you don't move because the digits after the comma with the float will change but the whole number will be the same and sometimes the digits after the comma will be the same. I think more digits is best but have a look and see and test test test test!!!!!!!

### CODE REVIEW

**Comment by itbeginshere** [comment]
I see the player can get shot with their own bullets, that is funnt. Not an issue though.

**Comment by itbeginshere** [comment]
I see the bullets disappear mid-air instead of falling to the ground.

**Comment by itbeginshere** [comment]
I can't hold down the mouse button to continuously shoot

**Comment by itbeginshere** [comment]
The time between shots does not seem to make a difference.

**Comment by itbeginshere** [comment]
Spread is cool

**Comment by itbeginshere** [comment]
Effective firing range does not change when the bullet disappears.

**Comment by itbeginshere** [comment]
Ah, bullets can destroy themselves... 
image

**Comment by SmallPeenwow** [comment]
Fook read the one thing wrong will complete tomorrow maybe or today but I have changed 2 variable names in Weapon script to be more descriptive and also there is now layer for bullets and bulletbehaviour script also checks to make sure object doesn't have bullet layer.

If does have bullet layer it will just bounce off gameobject.

Thumbs up next to eyes means its been done

**Comment by SmallPeenwow** [comment]
There is now a full auto. For when to want to hold down to fire make sure the gun has isFullAuto true. The other values will be used later on when doing switching between firing modes.

**Pull request merged**
